[colors.primary]
foreground = "#ECE1D7"
background = "#292522"
[colors.normal]
black      = "#34302C"
red        = "#BD8183"
green      = "#78997A"
yellow     = "#E49B5D"
blue       = "#7F91B2"
magenta    = "#B380B0"
cyan       = "#7B9695"
white      = "#C1A78E"
[colors.bright]
black      = "#867462"
red        = "#D47766"
green      = "#85B695"
yellow     = "#EBC06D"
blue       = "#A3A9CE"
magenta    = "#CF9BC2"
cyan       = "#89B3B6"
white      = "#ECE1D7"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"
SHELL = "/opt/homebrew/bin/fish"

[font]
size = 13.1
builtin_box_drawing = false

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[font.normal]
family = "MonoLisa Nerd Font Mono"

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
opacity = 1.0 
startup_mode = "Fullscreen"
dynamic_padding = true 
option_as_alt = "Both"
decorations_theme_variant = "Dark"

[window.padding]
x = 2
y = 0 

[hints]
alphabet = "hutenosadigpc.r,l'"

[[hints.enabled]]
regex = """(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
    [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
hyperlinks = true
command = ""
post_processing = true
mouse = { enabled = true }
binding = { key = "U", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[a-f0-9]{40}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }

[[hints.enabled]]
regex = """(/?[^/ \"']*[a-zA-Z0-9][^/ \"':]*/([^/ \"']+/?)*)\
    |(/[^/ \"']*[a-zA-Z0-9][^/ \"']*)"""
action = "Copy"
binding = { key = "P", mods = "Control|Shift" }

[keyboard]
bindings = [
  { key = "Escape", mods = "Command",                            action = "ToggleViMode"   },
  { key = "Escape",                              mode = "Vi|~Search", action = "ToggleViMode"   },
]

