[colors.primary]
foreground = "#ECE1D7"
background = "#292522"
[colors.normal]
black      = "#34302C"
red        = "#BD8183"
green      = "#78997A"
yellow     = "#E49B5D"
blue       = "#7F91B2"
magenta    = "#B380B0"
cyan       = "#7B9695"
white      = "#C1A78E"
[colors.bright]
black      = "#867462"
red        = "#D47766"
green      = "#85B695"
yellow     = "#EBC06D"
blue       = "#A3A9CE"
magenta    = "#CF9BC2"
cyan       = "#89B3B6"
white      = "#ECE1D7"

[env]
TERM = "alacritty"

[font]
size = 17.5

[font.bold]
family = "ZedMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font"
style = "Italic"

[font.normal]
family = "ZedMono Nerd Font"
style = "Extended"

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
opacity = 1.0
startup_mode = "Fullscreen"

[window.padding]
x = 10
y = 10
