[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c"] # TODO: ["h"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd" ]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "clang-format"}

[language-server.gopls]
command = "gopls"
args = []

[[language]]
name = "go"
language-servers = ["gopls"]
formatter = { command = "goimports" }
auto-format = true

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]


[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

# [language-server.emmet-lsp]
# command = "emmet-language-server"
# args = ["--stdio"]

# [[language]]
# name = "tsx"
# formatter = { command = "biome", args = ["--parser", "typescript"] }
# language-servers = ["typescript-language-server", "emmet-lsp"]

# [[language]]
# name = "html"
# roots = [".git"]
# formatter = { command = "biome", args = ["--parser", "html"] }
# language-servers = ["vscode-html-language-server", "emmet-lsp"]
